site_name: Python omfiles Documentation
site_description: Documentation for the omfiles Python package
site_author: Open-Meteo
repo_url: https://github.com/open-meteo/python-omfiles
repo_name: open-meteo/python-omfiles
copyright: GPL-2.0-only

nav:
  - Home: index.md
  - API Reference:
      - api.md
      - OmFilePyReader: api/reader.md
      - OmFilePyReaderAsync: api/readerasync.md
      - OmFilePyWriter: api/writer.md
      - types: api/types.md
      - xarray_backend: api/xarray.md

docs_dir: docs

theme:
  name: material
  # logo: images/logo.png # Optional: add a logo to docs/images/logo.png
  # favicon: images/favicon.ico # Optional: add a favicon to docs/images/favicon.ico
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - url: https://docs.xarray.dev/en/stable/objects.inv
              domains: [py]
            - url: https://numpy.org/doc/stable/objects.inv
              domains: [py]
            - url: https://filesystem-spec.readthedocs.io/en/latest/objects.inv
              domains: [py]
          load_external_modules: true
          options:
            find_stubs_package: true
            summary: true
            show_source: false
            docstring_style: google
            # docstring_section_style: list
            parameter_headings: true
            show_root_heading: true
            heading_level: 1
            show_symbol_type_heading: true
            filters:
              - "!__doc__"
              - "!__module__"
              - "!__new__"
              - "!__repr__"

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-meteo/python-omfiles
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/omfiles/
