name: Run cargo tests
description: Run cargo tests with uv and proper environment
runs:
  using: "composite"
  steps:
    - name: Run cargo tests
      shell: bash
      run: |
        # pyo3 and uv do not work well together...
        PY_LIBDIR=$(uv run --no-sync python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        echo "Python libdir: $PY_LIBDIR"
        # setting LD_LIBRARY_PATH for Linux: https://github.com/astral-sh/uv/issues/11006#issuecomment-2672486381
        export LD_LIBRARY_PATH="$PY_LIBDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" # LINUX
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          uv run --no-sync python -c "import sys; print(sys.path)"
          uv run --no-sync where python
          export PYTHONPATH="$(echo .venv/Lib/site-packages)"
        else
          # setting PYTHONHOME and PYTHONPATH seem to be the best solution for macOS at the moment
          # https://github.com/PyO3/pyo3/issues/1741#issuecomment-955805634
          export PYTHONHOME="$(uv run --no-sync python -c 'import sys; print(sys.base_prefix)')" # MACOS
          export PYTHONPATH="$(echo .venv/lib/python*/site-packages)" # MACOS
        fi
        uv run --no-sync cargo test --no-default-features
