name: Run cargo tests
description: Run cargo tests with uv and proper environment
inputs:
  extra-linux-env:
    description: Extra env for Linux (optional)
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Run cargo tests
      shell: bash
      run: |
        PY_LIBDIR=$(uv run --no-sync python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        echo "Python libdir: $PY_LIBDIR"
        export LD_LIBRARY_PATH="$PY_LIBDIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
        ${{ inputs.extra-linux-env }}
        uv run --no-sync cargo test --no-default-features
