name: "Build Package"
description: "Build wheels for all platforms"

inputs:
  target:
    description: "Target architecture"
    required: true
  manylinux:
    description: "Manylinux version"
    required: false
    default: ""
  is-musl:
    description: "Whether this is a musl build"
    required: false
    default: "false"
  before-script:
    description: "Script to run before building"
    required: false
    default: ""
  platform-name:
    description: "Platform name for artifact identification"
    required: true

runs:
  using: "composite"
  steps:
    # Cache Rust build artifacts
    - name: Cache Rust build
      uses: actions/cache@v4
      with:
        path: |
          target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-build-${{ inputs.platform-name }}-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ inputs.platform-name }}-

    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        args: --release --out dist --find-interpreter
        manylinux: ${{ inputs.manylinux }}
        container: ${{ inputs.is-musl == 'true' && 'off' || '' }}
        before-script-linux: ${{ inputs.before-script }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ inputs.platform-name }}
        path: dist
