name: "Run Tests"
description: "Install package and run tests"

inputs:
  skip_tests:
    description: "Skip running tests"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install package and run tests
      if: ${{ inputs.skip_tests != 'true' }}
      shell: bash
      run: |
        python -m pip install dist/*.whl
        python -m pip install ".[dev]"
        pytest tests/
