name: "Run Tests"
description: "Install package and run tests"

inputs:
  skip_tests:
    description: "Skip running tests"
    required: false
    default: "false"
  is_musl:
    description: "Whether this is a musl build"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run regular tests
      if: ${{ inputs.skip_tests != 'true' && inputs.is_musl != 'true' }}
      shell: bash
      run: |
        python -m pip install pytest
        WHEEL_PATH=$(ls dist/*.whl)
        python -m pip install --force-reinstall "$WHEEL_PATH"
        pytest tests/

    - name: Run musl tests
      if: ${{ inputs.skip_tests != 'true' && inputs.is_musl == 'true' }}
      uses: addnab/docker-run-action@v3
      with:
        image: alpine:latest
        options: -v ${{ github.workspace }}:/io -w /io
        run: |
          apk add python3 py3-pip
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          WHEEL_PATH=$(ls dist/*.whl)
          pip install --force-reinstall "$WHEEL_PATH"
          pip install pytest
          pytest tests/
